version: '3.8'

services:
    frontend:
        image: maplefighters/frontend:1.0.0
        ports:
            - 80:80
        depends_on:
            - character-service
            - game-service
            - gameprovider-service
            - chat-service
    character-service:
        image: maplefighters/character-service:1.0.0
        expose:
            - 50053
        depends_on:
            - postgres-character
        environment:
            RUST_LOG: info
            RUST_BACKTRACE: full
            IP_ADDRESS: 0.0.0.0:50053
            DATABASE_URL: postgres://${CHARACTER_DB_USER}:${CHARACTER_DB_PASSWORD}@postgres-character:5432/${CHARACTER_DB_NAME}
    game-service:
        image: maplefighters/game-service:1.0.0
        restart: "on-failure"
        expose:
            - 50051
        environment:
            URL: ws://0.0.0.0:50051
            FLECK_LOG: Info
            IM_LOG: Debug
            GAME_LOG: Debug
            CONFIG_SOURCE: v1.0
            MAX_CONNECTIONS: 100
    gameprovider-service:
        image: maplefighters/gameprovider-service:1.0.0
        expose:
            - 50052
        environment:
            RUST_LOG: info
            RUST_BACKTRACE: full
            IP_ADDRESS: 0.0.0.0:50052
            CONFIG_SOURCE: v1.0
            CONFIG_ENVIRONMENT: Production
    chat-service:
        image: maplefighters/chat-service:1.0.0
        expose:
            - 50054
        environment:
            PORT: 50054
    postgres-character:
        image: postgres:13
        restart: "always"
        expose:
            - 5432
        environment:
            POSTGRES_USER: ${CHARACTER_DB_USER}
            POSTGRES_PASSWORD: ${CHARACTER_DB_PASSWORD}
        volumes:
            - postgres:/var/lib/postgresql/data

volumes:
  postgres: ~
