version: '3.8'

services:
    frontend:
        image: frontend
        build:
            context: ./src/frontend
            dockerfile: Dockerfile
            args:
                ENVIRONMENT: Development
                NGINX_CONF_FILE: nginx.conf
        ports:
            - 80:80
        depends_on:
            - character-service
            - game-service
            - chat-service
    character-service:
        image: character-service
        build:
            context: ./src/character-service
        expose:
            - 50053
        depends_on:
            - postgres-character
        environment:
            RUST_LOG: info
            RUST_BACKTRACE: full
            IP_ADDRESS: 0.0.0.0:50053
            DATABASE_URL: postgres://postgres:postgres@postgres-character:5432/postgres
    game-service:
        image: game-service
        build:
            context: ./src/game-service/Game.Application
        restart: "on-failure"
        expose:
            - 50051
        environment:
            URL: ws://0.0.0.0:50051
            FLECK_LOG: Info
            IM_LOG: Debug
            GAME_LOG: Debug
            CONFIG_SOURCE: v1.0
            MAX_CONNECTIONS: 100
    chat-service:
        image: chat-service
        build:
            context: ./src/chat-service
        expose:
            - 50054
        environment:
            PORT: 50054
    postgres-character:
        image: postgres:13
        expose:
            - 5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
