version: '3.8'

services:
    frontend:
        image: maplefighters/frontend:2.0.0
        environment:
            REACT_APP_ENV: Production
            REMOVE_CF_IPS: "false"
        ports:
            - 443:443
        depends_on:
            - game-service
        volumes:
            - /etc/letsencrypt/live/maplefighters.io/server.crt:/etc/nginx/ssl/server.crt
            - /etc/letsencrypt/live/maplefighters.io/server.key:/etc/nginx/ssl/server.key
    game-service:
        image: maplefighters/game-service:2.0.0
        restart: "on-failure"
        expose:
            - 50051
        environment:
            URL: wss://0.0.0.0:50051
            FLECK_LOG: Info
            IM_LOG: Debug
            GAME_LOG: Debug
            CONFIG_SOURCE: v2.0
            MAX_CONNECTIONS: 100
            CERT_PASSWORD: ""
        volumes:
            - /etc/letsencrypt/live/maplefighters.io/server.pfx:/app/server.pfx
