version: '3.8'

services:
    frontend:
        image: frontend
        build:
            context: ./src/frontend
            dockerfile: Dockerfile
            args:
                ENVIRONMENT: Development
        environment:
            REMOVE_CF_IPS: true
        ports:
            - 80:80
        depends_on:
            - game-service
    game-service:
        image: game-service
        build:
            context: ./src/game-service/Game.Application
        restart: "on-failure"
        expose:
            - 50051
        environment:
            URL: ws://0.0.0.0:50051
            FLECK_LOG: Info
            IM_LOG: Debug
            GAME_LOG: Debug
            CONFIG_SOURCE: v2.0
            MAX_CONNECTIONS: 100
