apiVersion: v1
kind: Namespace
metadata:
  name: maple-fighters
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: maple-fighters
spec:
  ports:
  - name: chat-service-port
    port: 50054
    targetPort: 50054
  selector:
    app: chat-service
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: maple-fighters
spec:
  ports:
  - name: frontend-port
    port: 80
    targetPort: 80
  selector:
    app: frontend
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-external
  namespace: maple-fighters
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: game-service
  namespace: maple-fighters
spec:
  ports:
  - name: game-service-port
    port: 50051
    targetPort: 50051
  selector:
    app: game-service
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
  namespace: maple-fighters
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
      - env:
        - name: PORT
          value: "50054"
        image: maplefighters/chat-service:1.0.0
        imagePullPolicy: Always
        name: chat-service
        ports:
        - containerPort: 50054
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: maple-fighters
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: maplefighters/frontend:1.0.0
        imagePullPolicy: Always
        name: frontend
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 200m
            memory: 32Mi
          requests:
            cpu: 100m
            memory: 16Mi
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-service
  namespace: maple-fighters
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-service
  template:
    metadata:
      labels:
        app: game-service
    spec:
      containers:
      - env:
        - name: MAX_CONNECTIONS
          value: "100"
        - name: CONFIG_SOURCE
          value: v1.0
        - name: FLECK_LOG
          value: Info
        - name: GAME_LOG
          value: Debug
        - name: IM_LOG
          value: Debug
        - name: URL
          value: ws://0.0.0.0:50051
        image: maplefighters/game-service:1.0.0
        imagePullPolicy: Always
        name: game-service
        ports:
        - containerPort: 50051
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
      restartPolicy: Always
