name: Auth Service Build

on:
  push:
    branches: [v1.0]
    paths:
      - src/auth-service/**
  pull_request:
    branches: [v1.0]
    paths:
      - src/auth-service/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "5.0.x"
      - name: Authenticator API Build
        run: dotnet build src/auth-service/Authenticator.API -c Release
      - name: Authenticator Domain Build
        run: dotnet build src/auth-service/Authenticator.Domain -c Release
      - name: Authenticator Infrastructure Build
        run: dotnet build src/auth-service/Authenticator.Infrastructure -c Release
      - name: Authenticator Unit Tests Build
        run: dotnet build src/auth-service/Authenticator.UnitTests -c Release
      - name: Authenticator Unit Tests Run
        run: dotnet test src/auth-service/Authenticator.UnitTests -c Release
