name: Character Service Build

on:
  push:
    branches: [v1.0]
    paths:
      - src/character-service/**
  pull_request:
    branches: [v1.0]
    paths:
      - src/character-service/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Character App Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --manifest-path src/character-service/Cargo.toml
