name: Chat Service Build

on:
  push:
    branches: [v1.0]
    paths:
      - src/chat-service/**
  pull_request:
    branches: [v1.0]
    paths:
      - src/chat-service/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: src/chat-service/package-lock.json
      - name: Chat App Install
        run: npm ci --prefix src/chat-service
      - name: Chat App Build
        run: npm run build --prefix src/chat-service
