name: Frontend Build

on:
  push:
    branches: [v1.0]
    paths:
      - src/frontend/**
  pull_request:
    branches: [v1.0]
    paths:
      - src/frontend/**
  workflow_run:
    workflows: [Unity Build Updater]
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: src/frontend/package-lock.json
      - name: Frontend App Install
        run: npm ci --prefix src/frontend
      - name: Frontend App Build
        run: npm run build --prefix src/frontend
