name: Game Service Build

on:
  push:
    branches: [v1.0]
    paths:
      - src/game-service/Game.Application/**
      - src/game-service/Game.PhysicsTests/**
  pull_request:
    branches: [v1.0]
    paths:
      - src/game-service/Game.Application/**
      - src/game-service/Game.PhysicsTests/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "5.0.x"
      - name: Game Application Build
        run: dotnet build src/game-service/Game.Application -c Release
      - name: Game Physics Tests Build
        run: dotnet build src/game-service/Game.PhysicsTests -c Release
      - name: Game Unit Tests
        run: dotnet build src/game-service/Game.UnitTests -c Release
