name: Interest Management Build

on:
  push:
    branches: [main]
    paths:
      - lib/interest-management/**
  pull_request:
    branches: [main]
    paths:
      - lib/interest-management/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "5.0.x"
      - name: Build
        run: dotnet build lib/interest-management -c Release
