name: Interest Management Build

on:
  push:
    branches: [v1.0]
    paths:
      - lib/interest-management/**
  pull_request:
    branches: [v1.0]
    paths:
      - lib/interest-management/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "5.0.x"
      - name: Build
        run: dotnet build lib/interest-management -c Release
